### ISSUE TITLE
Can't compile the website

### ISSUE THREAD

**Issue by antho1404** [embark-framework/embark-plasma-demo#1]
When I do a fresh install from git, run `yarn install`, `embark run` and `yarn serve` I've got the following error

```
 ERROR  Failed to compile with 1 errors                                                              11:12:38 PM

This relative module was not found:

* ./embarkArtifacts/embarkjs in ./node_modules/cache-loader/dist/cjs.js??ref--120!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--00!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
```

Embark version: 4.0.2
Node: 10.16.0
Commit number: 744056c44f5c2df7b21ce5f7c83e4de72caafc4f

**Comment by emizzle** [comment]
Hey @antho1404 - have you tried using 4.1.0-beta.x via `npm i -g embark@next`? I just did a fresh install of embark + `embark-plasma-demo` and the site compiled.

**Comment by antho1404** [comment]
thanks, it works perfectly with the beta version 👍
